             CRTSQLRPGI OBJ(*CURLIB/POSTCLOBV)            +
                          SRCFILE(*CURLIB/QRPGLESRC)      +
                          SRCMBR(POSTCLOBV) COMMIT(*NONE) +
                          DBGVIEW(*SOURCE)

             CRTBNDRPG  PGM(*CURLIB/POSTCLOB_T)          +
                         SRCFILE(*CURLIB/QRPGLESRC)      +
                         SRCMBR(POSTCLOB_T)              +
                         DBGVIEW(*SOURCE)                +
                         REPLACE(*YES)